services:
  Abrouter\Client\Requests\RunExperimentRequest:
    class: Abrouter\Client\Requests\RunExperimentRequest
    autowire: true
  Abrouter\Client\Requests\RunFeatureFlagRequest:
    class: Abrouter\Client\Requests\RunFeatureFlagRequest
    autowire: true
  Abrouter\Client\Requests\SendEventRequest:
    class: Abrouter\Client\Requests\SendEventRequest
    autowire: true
  Abrouter\Client\DTO\BaseEventDTO:
    class: Abrouter\Client\DTO\BaseEventDTO
    autowire: true
  Abrouter\Client\DTO\EventDTO:
    class: Abrouter\Client\DTO\EventDTO
    autowire: true
  Abrouter\Client\DTO\IncrementalEventDTO:
      class: Abrouter\Client\DTO\IncrementalEventDTO
      autowire: true
  Abrouter\Client\DTO\SummarizeEventDTO:
      class: Abrouter\Client\DTO\SummarizeEventDTO
      autowire: true
  Abrouter\Client\Builders\Payload\ExperimentRunPayloadBuilder:
    class: Abrouter\Client\Builders\Payload\ExperimentRunPayloadBuilder
    autowire: true
  Abrouter\Client\Builders\Payload\FeatureFlagRunPayloadBuilder:
    class: Abrouter\Client\Builders\Payload\FeatureFlagRunPayloadBuilder
    autowire: true
  Abrouter\Client\Builders\Payload\SendEventPayloadBuilder:
    class: Abrouter\Client\Builders\Payload\SendEventPayloadBuilder
    autowire: true
  Abrouter\Client\Transformers\RunExperimentRequestTransformer:
    class: Abrouter\Client\Transformers\RunExperimentRequestTransformer
    autowire: true
  Abrouter\Client\Transformers\RunFeatureFlagRequestTransformer:
    class: Abrouter\Client\Transformers\RunFeatureFlagRequestTransformer
    autowire: true
  Abrouter\Client\Transformers\SendEventRequestTransformer:
    class: Abrouter\Client\Transformers\SendEventRequestTransformer
    autowire: true
  Abrouter\Client\Config\Accessors\TokenConfigAccessor:
    class: Abrouter\Client\Config\Accessors\TokenConfigAccessor
    autowire: true
  Abrouter\Client\Builders\RequestBuilder:
    class: Abrouter\Client\Builders\RequestBuilder
    autowire: true
  Abrouter\Client\Builders\UrlBuilder:
    class: Abrouter\Client\Builders\UrlBuilder
    autowire: true
  Abrouter\Client\Http\RequestExecutor:
    class: Abrouter\Client\Http\RequestExecutor
    autowire: true
  Abrouter\Client\Config\Accessors\HostConfigAccessor:
    class: Abrouter\Client\Config\Accessors\HostConfigAccessor
    autowire: true
  GuzzleHttp\Client:
    class: GuzzleHttp\Client
    autowire: true
  Abrouter\Client\Manager\ExperimentManager:
    class: Abrouter\Client\Manager\ExperimentManager
    autowire: true
  Abrouter\Client\Manager\FeatureFlagManager:
    class: Abrouter\Client\Manager\FeatureFlagManager
    autowire: true
  Abrouter\Client\Manager\StatisticsManager:
    class: Abrouter\Client\Manager\StatisticsManager
    autowire: true
  Abrouter\Client\Client: '@abrouter_client.client'
  abrouter_client.client:
    class: Abrouter\Client\Client
    autowire: true
